var firstName = "Sidra";
var secondName = "Raza";
var define = "is year old";
var age = 21;
var result = "".concat(firstName + " " + secondName, " is ").concat(age, " years old");
console.log(result);
var num1 = 5;
var num2 = 4;
var total = num1 + num2;
console.log(total);
var num3 = 5;
var num4 = 4;
var num13 = num3 - num4;
console.log(num13);
var num5 = 5;
var num6 = 4;
var num14 = num5 / num6;
console.log(num14);
var num7 = 5;
var num8 = 4;
var num15 = num7 * num8;
console.log(num15);
var num9 = 5;
var num10 = 4;
var num16 = Math.pow(num9, num10);
console.log(num16);
var num11 = 5;
var num12 = 4;
var num17 = num11 % num12;
console.log(num17);
var year = 2024;
var leap = 4;
var check = year % leap;
console.log(check);
var a = 5;
var b = 2;
var c;
c = ++a + a++ + --b + b-- + a + b++ + b;
console.log(c);
6 + 7 + 1 + 0 + 5 + 1 + 2;
